# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================

spring:
    profiles: customized_pool
fdfs:
  soTimeout: 1501
  connectTimeout: 601 
  thumbImage:
    width: 150
    height: 150
  trackerList:
     - 119.23.21.230:22122
  pool:
    #从池中借出的对象的最大数目
    maxTotal: 153
    #获取连接时的最大等待毫秒数100
    maxWaitMillis: 102
